package com.configurator.entity;

public enum PropertyName {
    CHOOSE_ROOM_STATUS,
    MAX_NUMBER_OF_LAST_ROOM_GUESTS,
    ROOM_PATH_FILE,
    SERIALIZABLE_PATH_FILE,
    IGUESTSTORAGE,
    IROOMSTORAGE,
    ISERVICESTORAGE,
    IGUESTROOMINFOSTORAGE,
    IGUESTSERVICESTORAGE,
    ISERIALIZABLE,
    IPROPERTYSERVICE,
    IFILESERVICE,
    IPRINTERSERVICE,
    ICONFIGURATOR,
    IGUESTSERVICE,
    IROOMSERVICE,
    ISERVICESERVICE,
    IHOTELCONTROLLER
}
